edition = "2018"
max_width = 100
newline_style = "Unix"
reorder_imports = true
control_brace_style = "ClosingNextLine"
fn_args_layout = "Compressed"
empty_item_single_line = false
hard_tabs = true
merge_imports = true
merge_derives = true
reorder_modules = true
reorder_impl_items = true
tab_spaces = 4
format_strings = true
space_before_colon = true
space_after_colon = true
