[flags]
avg_cpu = true

# Temperature is one of:
temperature_type = "c"

rate = 1000
cpu_left_legend = false
current_usage = false
group_processes = false
case_sensitive = false
whole_word = false
regex = true
default_widget_type = "cpu"
default_widget_count = 1

[styles]
theme = "gruvbox"

[processes]
columns = ["PID", "Name", "CPU%", "Mem%", "Rps", "Wps", "TRead", "TWrite", "State", "Time", "Virt"]
